[project]
name = "maskbench"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src", "src.common", "src.masking", "src.common.plot_utils"]
package-dir = {"" = "."}